# Generated by Django 2.0.6 on 2018-06-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='node_id',
        ),
        migrations.AddField(
            model_name='sensor',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_id',
            field=models.IntegerField(default=0),
        ),
    ]
