# Generated by Django 2.0.6 on 2018-07-01 19:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('remote_server', '0003_auto_20180701_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='date',
        ),
        migrations.AddField(
            model_name='pump',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 1, 19, 37, 16, 61459, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 1, 19, 37, 16, 61134, tzinfo=utc)),
        ),
    ]
